### ISSUE TITLE
DungeonAuraTools/Options.lua:483: attempt to concatenate local 'EncounterName' (a nil value)

### ISSUE THREAD

**Issue by d4kir92** [Jodsderechte/DungeonAuraTools#79] opened 2023-01-09 15:01 UTC
### Description

Got an error on login/reload

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.1.6

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Lua Error

2x DungeonAuraTools/Options.lua:483: attempt to concatenate local 'EncounterName' (a nil value)
[string "@DungeonAuraTools/Options.lua"]:483: in function `createOptionsData'
[string "@DungeonAuraTools/Main.lua"]:301: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@WeakAuras/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <WeakAuras/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

### Reproduction Steps

Login

### Saved Variables

DungeonAuraTools = {
	["profileKeys"] = {
		["Jolon - Arthas"] = "Default",
	},
}

**Comment by Jodsderechte** [comment] 2023-01-09 16:53
Duplicate of #78 also true i do not need to change the color of the first letter

**Closed by Jodsderechte** 2023-01-09 16:53 UTC
Labels: bug
