### ISSUE TITLE
LUA errors upon login and typing /dat

### ISSUE THREAD

**Issue by crusha015** [Jodsderechte/DungeonAuraTools#78] opened 2023-01-06 13:52 UTC
### Description

I am getting LUA errors upon login and also when typing /dat to attempt to bring up the options window.

This just started happening within the last couple days.

After testing with only DungeonAuraTools and WeakAuras enabled, I do not encounter the errors. I tested turning addons back one at a time, and the error returned when I re-enabled Details Damage Meter.

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.1.6

### Tested with only WeakAuras and DungeonAuraTools

- [X] Yes
- [ ] No

### Lua Error

Upon login I get the following error message:

Message: Interface/AddOns/DungeonAuraTools/Options.lua:483: attempt to concatenate local 'EncounterName' (a nil value)
Time: Fri Jan  6 07:38:57 2023
Count: 1
Stack: Interface/AddOns/DungeonAuraTools/Options.lua:483: attempt to concatenate local 'EncounterName' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/DungeonAuraTools/Options.lua"]:483: in function `createOptionsData'
[string "@Interface/AddOns/DungeonAuraTools/Main.lua"]:301: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: 

If I type /dat to attempt to bring up options, I get the following error message and the options do not appear:

Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1854: AceConfigRegistry-3.0:ValidateOptionsTable(): DungeonAuraTools.args.rest.args.spelloptions.args.Legion.args.ReturnToKarazhan.args.boss5.name: expected a string or funcref, got 'nil'
Time: Fri Jan  6 07:42:20 2023
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1854: AceConfigRegistry-3.0:ValidateOptionsTable(): DungeonAuraTools.args.rest.args.spelloptions.args.Legion.args.ReturnToKarazhan.args.boss5.name: expected a string or funcref, got 'nil'
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:50: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:45>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:211: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:206>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:245: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:283: in function `ValidateOptionsTable'
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:325: in function `app'
[string "@Interface/AddOns/AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1854: in function `Open'
[string "@Interface/AddOns/DungeonAuraTools/Main.lua"]:48: in function `CreateOptionsFrame'
[string "@Interface/AddOns/DungeonAuraTools/Main.lua"]:295: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConsole-3.0/AceConsole-3.0.lua"]:90: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4924: in function <Interface/FrameXML/ChatFrame.lua:4920>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals: 

### Reproduction Steps

Logging in immediately produces the first error.

Typing /dat produces the second error.

### Saved Variables

[DungeonAuraTools.txt](https://github.com/Jodsderechte/DungeonAuraTools/files/10360569/DungeonAuraTools.txt)

### Last Good Version

5.3.4

**Comment by crusha015** [comment] 2023-01-06 14:02
Upon further testing with various addon combinations loaded, it appears that the issue is not being caused by ElvUI.

The errors return as soon as I load the Details Damage Meter addon, which had a new release pushed on 1/5 and that is when I began seeing these errors.

**Comment by Beet4** [comment] 2023-01-06 21:29
Can confirm I have also started getting LUA errors upon logging in:
```
5x DungeonAuraTools/Options.lua:483: attempt to concatenate local 'EncounterName' (a nil value)
[string "@DungeonAuraTools/Options.lua"]:483: in function `createOptionsData'
[string "@DungeonAuraTools/Main.lua"]:301: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Dragonflight = <table> {
 }
 Legion = <table> {
 }
 Affixes = <table> {
 }
 Shadowlands = <table> {
 }
 BattleForAzeroth = <table> {
 }
 MistOfPandaria = <table> {
 }
 WarlordOfDraenor = <table> {
 }
}
(for control) = "Legion"
ExpansionKey = "Legion"
ExpansionValue = <table> {
 Dungeons = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 ReturnToKarazhan = <table> {
 }
 CourtOfStars = <table> {
 }
 HallsOfValor = <table> {
 }
}
(for control) = "ReturnToKarazhan"
DungeonKey = "ReturnToKarazhan"
DungeonValue = <table> {
 Bosses = <table> {
 }
 zoneId = "g260"
 groupName = "[KARAZHAN "
 EncounterJournalID = 860
}
Instancename = "Brackenhide Hollow"
Instancedescription = "Brackenhide Hollow is the largest gnoll settlement in the Dragon Isles, and home to unspeakable danger. Decay seeps from the Hollow, spreading among the gnoll tribes of the Azure Span and threatening to rot away all life. In the heart of the Hollow lies the leader of the Brackenhide, and the knowledge she gleefully shares with her withered kin."
_ = 4742820
buttonImage1 = 4742923
_ = 4742933
_ = 4746635
_ = 2096
_ = "|cff66bbff|Hjournal:0:1196:1|h[Brackenhide Hollow]|h|r"
_ = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 boss5 = <table> {
 }
 boss8 = <table> {
 }
 Trash = <table> {
 }
 boss9 = <table> {
 }
 boss10 = <table> {
 }
 boss4 = <table> {
 }
 boss6 = <table> {
 }
 boss1 = <table> {
 }
 boss3 = <table> {
 }
 boss2 = <table> {
 }
 boss7 = <table> {
 }
}
(for control) = "boss5"
BossNameKey = "boss5"
BossNameValue = <table> {
 EncounterId = "1960"
 Auras = <table> {
 }
 additionalName = " - LOWER] 03 "
}
EncounterName = nil
Encounterdescription = nil
journalEncounterID = nil
rootSectionID = nil
link = nil
journalInstanceID = nil
dungeonEncounterID = nil
instanceID = nil
id = nil
name = nil
description = nil
displayInfo = nil
iconImage = nil
uiModelSceneID = nil
OrderNumber = 5
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "Toggles all Auras for"
(*temporary) = " "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = EncounterJournalEncounterFrameInfoOverviewTab {
 0 = <userdata>
 unselected = EncounterJournalEncounterFrameInfoOverviewTabUnselect {
 }
 Point = <function> defined =[C]:-1
 __windShadow = 2
 tooltip = "Overview"
 backdrop = Frame {
 }
 selected = EncounterJournalEncounterFrameInfoOverviewTabSelect {
 }
}
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined *Blizzard_EncounterJournal.xml:2084_OnClick:1
(*temporary) = EncounterJournalEncounterFrameInfoOverviewTab {
 0 = <userdata>
 unselected = EncounterJournalEncounterFrameInfoOverviewTabUnselect {
 }
 Point = <function> defined =[C]:-1
 __windShadow = 2
 tooltip = "Overview"
 backdrop = Frame {
 }
 selected = EncounterJournalEncounterFrameInfoOverviewTabSelect {
 }
}
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined @Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua:937
(*temporary) = 1196
(*temporary) = true
(*temporary) = 1
(*temporary) = "attempt to concatenate local 'EncounterName' (a nil value)"
JDT = <table> {
 SoundTypes = <table> {
 }
 buildDataToExport = <function> defined @DungeonAuraTools/Export.lua:75
 getLocalisation = <function> defined @DungeonAuraTools/Locales.lua:4
 InternalWaVersion = 61
 CreateOptionsFrame = <function> defined @DungeonAuraTools/Main.lua:47
 Templates = <table> {
 }
 db = <table> {
 }
 exportAuras = <function> defined @DungeonAuraTools/Export.lua:2
 CheckIfAuraUpdates = <function> defined @DungeonAuraTools/Main.lua:52
 AuraTypes = <table> {
 }
 DataToExport = <table> {
 }
 ExpansionValues = <table> {
 }
 CallbackFunc = <function> defined @DungeonAuraTools/Export.lua:8
 createOptionsData = <functi
```

And LUA error on /dat: (window does not open at all):
```
3x ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:1854: AceConfigRegistry-3.0-21:ValidateOptionsTable(): DungeonAuraTools.args.rest.args.spelloptions.args.Legion.args.ReturnToKarazhan.args.boss5.name: expected a string or funcref, got 'nil'
[string "=[C]"]: ?
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:50: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:45>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:211: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:206>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:245: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:283: in function `ValidateOptionsTable'
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:325: in function `app'
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1854: in function `Open'
[string "@DungeonAuraTools/Main.lua"]:48: in function `CreateOptionsFrame'
[string "@DungeonAuraTools/Main.lua"]:295: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4924: in function <FrameXML/ChatFrame.lua:4920>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
(*temporary) = "AceConfigRegistry-3.0:ValidateOptionsTable(): DungeonAuraTools.args.rest.args.spelloptions.args.Legion.args.ReturnToKarazhan.args.boss5.name: expected a string or funcref, got 'nil'"

```

**Comment by Jodsderechte** [comment] 2023-01-07 08:40
this seems to be a confirmed issue with Details! caching the encounter journal data since i'm mid exams i have no time to fix it right now and it seems like Terico is aware and will try to fix it regardlessly. If not i'll fix it as soon as i get time but for now you guys can just revert to a details version before yesterday (or disable details quickly if you want to use the addon)

**Comment by Jodsderechte** [comment] 2023-01-07 12:42
should be fixed by terico in next release

**Closed by Jodsderechte** 2023-01-07 12:42 UTC
Labels: bug

**Comment by Beet4** [comment] 2023-01-07 13:20
Awesome, thank you for your efforts and good luck with your exams :)
